technologyWebApp/Controllers/LogİnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using technologyWebApp.Models;
namespace technologyWebApp.Controllers
{
    public class LogİnController : Controller
    {
        
        // GET: Logİn
        technologyWebSiteDBEntities1 entity1 = new technologyWebSiteDBEntities1();


        public ActionResult Index()

        {
            ViewBag.mesaj = null;
            return View();
        }
        [HttpPost]
        public ActionResult Index(string userName, string userPassword)
        {

            var Users = (from u in entity1.Users where u.usNickname == userName && u.usPassword == userPassword select u).FirstOrDefault();
            if (Users != null)
            {

                Session["usName"] = Users.usNickname;
                Session["usID"] = Users.usID;
                Session["usType"] = Users.usType;

                switch (Users.usType)
                {
                    case 1:
                        return RedirectToAction("Index", "Yönetici");

                    case 2:
                        return RedirectToAction("Index", "Kullanıcı");                             // database de değişken türünü bitdfen inte çevir
                    default:
                        return View();
                }

            }
            else
            {
                ViewBag.mesaj = "Kullanıcı adı yada Parola yanlış";
                return View();
            }



        }
        

       








    }
}

technologyWebApp/Views/Logİn/Index.cshtml
@{
    Layout = null;
}




<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
   
    <title>Tech MADT Giriş</title>
   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/sign-in.css" rel="stylesheet" />
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
       <main class="form-signin w-100 m-auto">
        @using (Html.BeginForm("Index", "Logİn", FormMethod.Post))
        {
            <h1 class="h3 mb-3 fw-normal">Tech MADT Giriş Sayfası</h1>
            <br/>
            <div class="form-floating"> <input type="text" class="form-control" id="userName" name="userName" >
           <label for="userName">Kullanıcı Adınız</label> </div>
            <br/>
            <div class="form-floating"> <input type="password" class="form-control" id="userPassword" name="userPassword">
           <label for="userPassword">Parola</label> 
                </div> 
            <br/>
            <button class="btn btn-primary w-100 py-2" type="submit">Giriş</button> 

            <br/><br/>
            <u>@ViewBag.mesaj</u>
        }
    </main>
    
</body>
</html>